backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/data/home/home.md"
        label: "Homepage Content"
        name: "home_content"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Introduction"
            name: "introduction"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "hidden", default: "introduction" }
              - { label: "Navigation Title", name: "nav_title", widget: "string", required: false }
              - { label: "Intro Field 1", name: "introField1", widget: "string" }
              - { label: "Intro Field 2", name: "introField2", widget: "string" }
              - { label: "Intro Visual", name: "media", widget: "file", required: true, media_library: { allow_multiple: false, type: ["image/*", "video/mp4"] } }
          - label: "How We Get Down"
            name: "largeParagraph"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "hidden", default: "how-we-get-down" }
              - { label: "Content", name: "content", widget: "markdown", required: true }
              - { label: "Navigation Title", name: "nav_title", widget: "string", required: false }
          - label: "What We Do"
            name: "whatwedo"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "hidden", default: "what-we-do" }
              - { label: "Navigation Title", name: "nav_title", widget: "string", required: false }
              - label: "What We Do Pages"
                name: "pages"
                widget: "list"
                hint: "This section allows you to define the different pages under 'What We Do'. Each page can have a title, content, and up to four media items (images or videos) with custom Tailwind CSS classes and descriptions."
                fields:
                  - { label: "Title", name: "title", widget: "string", required: true }
                  - { label: "Content", name: "content", widget: "markdown", required: true }
                  - { label: "Tailwind CSS Classes Media 1", name: "media1_css", widget: "string", required: false }
                  - { label: "Description (Alt tag) Media 1", name: "media1_description", widget: "string", required: false }
                  - { label: "Media 1", name: "media1", widget: "file", required: false, media_library: { allow_multiple: false, type: ["image/*", "video/mp4"] } }
                  - { label: "Tailwind CSS Classes Media 2", name: "media2_css", widget: "string", required: false }
                  - { label: "Description (Alt tag) Media 2", name: "media2_description", widget: "string", required: false }
                  - { label: "Media 2", name: "media2", widget: "file", required: false, media_library: { allow_multiple: false, type: ["image/*", "video/mp4"] } }
                  - { label: "Tailwind CSS Classes Media 3", name: "media3_css", widget: "string", required: false }
                  - { label: "Description (Alt tag) Media 3", name: "media3_description", widget: "string", required: false }
                  - { label: "Media 3", name: "media3", widget: "file", required: false, media_library: { allow_multiple: false, type: ["image/*", "video/mp4"] } }
                  - { label: "Tailwind CSS Classes Media 4", name: "media4_css", widget: "string", required: false }
                  - { label: "Description (Alt tag) Media 4", name: "media4_description", widget: "string", required: false }
                  - { label: "Media 4", name: "media4", widget: "file", required: false, media_library: { allow_multiple: false, type: ["image/*", "video/mp4"] } }
          - label: "You Heard?"
            name: "quotes"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "hidden", default: "you-heard" }
              - { label: "Navigation Title", name: "nav_title", widget: "string", required: false }
              - label: "Quotes List"
                name: "quotes"
                widget: "list"
                fields:
                  - { label: "Quote", name: "quote", widget: "string", required: true }
                  - { label: "Author", name: "author", widget: "string", required: true }
              - label: "Additional Paragraph"
                name: "additionalParagraph"
                widget: "object"
                fields:
                  - { label: "Content", name: "content", widget: "markdown", required: false }
          - label: "Our Latest Work"
            name: "projects"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "hidden", default: "work" }
              - { label: "Navigation Title", name: "nav_title", widget: "string", required: false }
              - label: "Projects List"
                name: "projects"
                widget: "relation"
                collection: "projects"
                multiple: true
                search_fields: ["title"]
                value_field: "title"
                display_fields: ["title"]
          - label: "Connect & Politics"
            name: "footer"
            widget: "object"
            fields:
              - { label: "ID", name: "id", widget: "hidden", default: "connect" }
              - { label: "Navigation Title", name: "nav_title", widget: "string", required: false }
              - { label: "Footer Field 1", name: "footerField1", widget: "string" }
              - { label: "Footer Field 2", name: "footerField2", widget: "string" }
              - { label: "Footer Field 3", name: "footerField3", widget: "string" }
              - { label: "Footer Visual", name: "media", widget: "file", required: true, media_library: { allow_multiple: false, type: ["image/*", "video/mp4"] } }

  - name: "projects"
    label: "Manage Projects"
    folder: "src/data/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "hidden", default: "{{slug}}" }  # Hidden field for ID using slug
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Hero Visual", name: "media", widget: "file", required: true, media_library: { allow_multiple: false, type: ["image/*", "video/mp4"] } }
      - label: "Logos"
        name: "logos"
        widget: "list"
        hint: "Up to 8 logos."
        field:
          { label: "Logo", name: "detailed_logos", widget: "image", required: false }
      - label: "Quote"
        name: "detailed_quote"
        widget: "object"
        fields:
          - { label: "Quote", name: "detailed_quote_content", widget: "markdown", required: true }
          - { label: "Author", name: "detailed_quote_content_auth", widget: "string", required: false }
  
