backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "src/data/home/home.md"
        label: "Homepage Content"
        name: "home_content"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Introduction"
            name: "introduction"
            widget: "object"
            fields:
              - { label: "Field 1", name: "field1", widget: "string" }
              - { label: "Field 2", name: "field2", widget: "string" }
              - { label: "Intro Visual", name: "media", widget: "file", required: false, media_library: { allow_multiple: false, type: ["image/*", "video/mp4"] } }
          - label: "Sections"
            name: "sections"
            widget: "list"
            types:
              - label: "Large Paragraph"
                name: "largeParagraph"
                widget: "object"
                fields:
                  - { label: "Content", name: "content", widget: "markdown" }
              - label: "Quotes"
                name: "quotes"
                widget: "object"
                fields:
                  - label: "Quotes List"
                    name: "quotes"
                    widget: "list"
                    fields:
                      - { label: "Quote", name: "quote", widget: "string" }
                      - { label: "Author", name: "author", widget: "string" }
                  - label: "Additional Paragraph"
                    name: "additionalParagraph"
                    widget: "object"
                    fields:
                      - { label: "Content", name: "content", widget: "markdown" }
              - label: "Projects"
                name: "projects"
                widget: "object"
                fields:
                  - label: "Projects List"
                    name: "projects"
                    widget: "relation"
                    collection: "projects"
                    multiple: true
                    search_fields: ["title"]
                    value_field: "title"
                    display_fields: ["title"]
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - { label: "Field 1", name: "field1", widget: "string" }
              - { label: "Field 2", name: "field2", widget: "string" }
              - { label: "Field 3", name: "field3", widget: "string" }
              - { label: "Footer Visual", name: "media", widget: "file", required: false, media_library: { allow_multiple: false, type: ["image/*", "video/mp4"] } }

  - name: "projects"
    label: "Projects"
    folder: "src/data/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Hero Visual", name: "media", widget: "file", required: false, media_library: { allow_multiple: false, type: ["image/*", "video/mp4"] } }
