backend:
  name: git-gateway
  branch: main # Branch to update (use `main` if your default branch is `main`)

media_folder: "public/images/uploads" # Folder where user uploads go
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "data/home/home.md"
        label: "Homepage Content"
        name: "home_content"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "Sections"
            name: "sections"
            widget: "list"
            types:
              - label: "Introduction"
                name: "introduction"
                widget: "object"
                fields:
                  - { label: "Field 1", name: "field1", widget: "string" }
                  - { label: "Field 2", name: "field2", widget: "string" }
              - label: "Large Paragraph"
                name: "largeParagraph"
                widget: "object"
                fields:
                  - { label: "Content", name: "content", widget: "markdown" }
              - label: "Quotes"
                name: "quotes"
                widget: "object"
                fields:
                  - label: "Quotes List"
                    name: "quotes"
                    widget: "list"
                    fields:
                      - { label: "Quote", name: "quote", widget: "string" }
                      - { label: "Author", name: "author", widget: "string" }
